name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Run Openfire
        uses: igniterealtime/launch-openfire-action@v1.2.0
        with:
          daily: 'true'

      - uses: ./.github/actions/run-tests
